application: gridtodo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /media
  static_dir: media
- url: /.*
  script: gridtodo.app
libraries:
- name: jinja2
  version: latest
inbound_services:
- channel_presence
